version: "3.8"

services:
  gameserver:
    image: andersgee/websocketgame-rust-server
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - $PORT_EXPOSED:$PORT
    expose:
      - $PORT_EXPOSED
